/**
 * Localized scaffolding for the deterministic generation engine, so try-it and
 * generated assets read in the user's chosen language. Fields are the fixed
 * template phrases the engine wraps around the user's own (already-localized)
 * content. Missing locales fall back to English.
 */
export interface GenLabels {
  typeYoutubeShort: string;
  typeTiktokClip: string;
  typeInstagramReel: string;
  typeCarousel: string;
  typeNewsletter: string;
  typeThread: string;
  nameCarousel: string;
  nameNewsletter: string;
  nameThread: string;
  hook: string; // "HOOK (0:00–0:03):"
  body: string; // "BODY:"
  caption: string; // "ON-SCREEN CAPTION:"
  ctaFollow: string; // "Follow for more on" (+ topic)
  hashtags: string;
  fallback: string; // "{topic}: " + this
  slidesWord: string;
  slide: string;
  hookWord: string;
  ctaWord: string;
  carouselCta: string;
  newsletterEdition: string;
  subject: string;
  newsletterIntro: string;
  takeaways: string;
  newsletterOutro: string;
  threadHeader: string;
  threadOpen: string; // "{topic} — " + this
  threadClose: string;
}

const en: GenLabels = {
  typeYoutubeShort: "YouTube Short",
  typeTiktokClip: "TikTok Clip",
  typeInstagramReel: "Instagram Reel",
  typeCarousel: "LinkedIn Carousel",
  typeNewsletter: "Newsletter",
  typeThread: "X Thread",
  nameCarousel: "Carousel",
  nameNewsletter: "Newsletter",
  nameThread: "Thread",
  hook: "HOOK (0:00–0:03):",
  body: "BODY:",
  caption: "ON-SCREEN CAPTION:",
  ctaFollow: "Follow for more on",
  hashtags: "#shorts #creator",
  fallback: "the core ideas, condensed for short-form.",
  slidesWord: "slides",
  slide: "Slide",
  hookWord: "Hook",
  ctaWord: "CTA",
  carouselCta: "Save this for later — follow for more.",
  newsletterEdition: "Newsletter Edition",
  subject: "Subject:",
  newsletterIntro: "Here's the one idea worth your time this week.",
  takeaways: "Three takeaways:",
  newsletterOutro: "That's it for this week — reply and tell me what landed.",
  threadHeader: "X / Twitter Thread",
  threadOpen: "a thread 👇",
  threadClose: "If this helped, repost the first tweet.",
};

// Non-English locales are merged in below; anything missing falls back to `en`.
export const GEN_LABELS: Record<string, GenLabels> = {
  en,
  "es": {
    typeYoutubeShort: "YouTube Short",
    typeTiktokClip: "Clip de TikTok",
    typeInstagramReel: "Instagram Reel",
    typeCarousel: "Carrusel de LinkedIn",
    typeNewsletter: "Newsletter",
    typeThread: "Hilo de X",
    nameCarousel: "Carrusel",
    nameNewsletter: "Newsletter",
    nameThread: "Hilo",
    hook: "GANCHO (0:00–0:03):",
    body: "CUERPO:",
    caption: "TEXTO EN PANTALLA:",
    ctaFollow: "Sigue para más sobre",
    hashtags: "#shorts #creator",
    fallback: "las ideas clave, condensadas para formato corto.",
    slidesWord: "diapositivas",
    slide: "Diapositiva",
    hookWord: "Gancho",
    ctaWord: "CTA",
    carouselCta: "Guárdalo para después — sigue para más.",
    newsletterEdition: "Edición del Newsletter",
    subject: "Asunto:",
    newsletterIntro: "Aquí está la única idea que merece tu tiempo esta semana.",
    takeaways: "Tres conclusiones:",
    newsletterOutro: "Eso es todo por esta semana — responde y cuéntame qué te llegó.",
    threadHeader: "Hilo de X / Twitter",
    threadOpen: "un hilo 👇",
    threadClose: "Si te sirvió, republica el primer tweet.",
  },
  "fr": {
    typeYoutubeShort: "YouTube Short",
    typeTiktokClip: "Clip TikTok",
    typeInstagramReel: "Instagram Reel",
    typeCarousel: "Carrousel LinkedIn",
    typeNewsletter: "Newsletter",
    typeThread: "Thread X",
    nameCarousel: "Carrousel",
    nameNewsletter: "Newsletter",
    nameThread: "Thread",
    hook: "ACCROCHE (0:00–0:03) :",
    body: "CORPS :",
    caption: "TEXTE À L'ÉCRAN :",
    ctaFollow: "Abonnez-vous pour plus sur",
    hashtags: "#shorts #creator",
    fallback: "les idées essentielles, condensées pour le format court.",
    slidesWord: "diapos",
    slide: "Diapo",
    hookWord: "Accroche",
    ctaWord: "CTA",
    carouselCta: "Enregistrez-le pour plus tard — abonnez-vous pour plus.",
    newsletterEdition: "Édition de la newsletter",
    subject: "Objet :",
    newsletterIntro: "Voici la seule idée qui mérite votre temps cette semaine.",
    takeaways: "Trois points à retenir :",
    newsletterOutro: "C'est tout pour cette semaine — répondez et dites-moi ce qui vous a marqué.",
    threadHeader: "Thread X / Twitter",
    threadOpen: "un thread 👇",
    threadClose: "Si ça vous a aidé, repartagez le premier tweet.",
  },
  "de": {
    typeYoutubeShort: "YouTube Short",
    typeTiktokClip: "TikTok-Clip",
    typeInstagramReel: "Instagram Reel",
    typeCarousel: "LinkedIn-Karussell",
    typeNewsletter: "Newsletter",
    typeThread: "X-Thread",
    nameCarousel: "Karussell",
    nameNewsletter: "Newsletter",
    nameThread: "Thread",
    hook: "HOOK (0:00–0:03):",
    body: "HAUPTTEIL:",
    caption: "BILDSCHIRMTEXT:",
    ctaFollow: "Folge für mehr zu",
    hashtags: "#shorts #creator",
    fallback: "die Kernideen, verdichtet fürs Kurzformat.",
    slidesWord: "Slides",
    slide: "Slide",
    hookWord: "Hook",
    ctaWord: "CTA",
    carouselCta: "Speichere es für später — folge für mehr.",
    newsletterEdition: "Newsletter-Ausgabe",
    subject: "Betreff:",
    newsletterIntro: "Hier ist die eine Idee, die diese Woche deine Zeit wert ist.",
    takeaways: "Drei Erkenntnisse:",
    newsletterOutro: "Das war's für diese Woche — antworte und sag mir, was hängen geblieben ist.",
    threadHeader: "X / Twitter Thread",
    threadOpen: "ein Thread 👇",
    threadClose: "Wenn es geholfen hat, teile den ersten Tweet erneut.",
  },
  "pt": {
    typeYoutubeShort: "YouTube Short",
    typeTiktokClip: "Clipe do TikTok",
    typeInstagramReel: "Instagram Reel",
    typeCarousel: "Carrossel do LinkedIn",
    typeNewsletter: "Newsletter",
    typeThread: "Thread no X",
    nameCarousel: "Carrossel",
    nameNewsletter: "Newsletter",
    nameThread: "Thread",
    hook: "GANCHO (0:00–0:03):",
    body: "CORPO:",
    caption: "LEGENDA NA TELA:",
    ctaFollow: "Siga para mais sobre",
    hashtags: "#shorts #creator",
    fallback: "as ideias centrais, condensadas para o formato curto.",
    slidesWord: "slides",
    slide: "Slide",
    hookWord: "Gancho",
    ctaWord: "CTA",
    carouselCta: "Salve para depois — siga para mais.",
    newsletterEdition: "Edição da Newsletter",
    subject: "Assunto:",
    newsletterIntro: "Aqui está a única ideia que vale seu tempo esta semana.",
    takeaways: "Três aprendizados:",
    newsletterOutro: "É isso por esta semana — responda e me conte o que fez sentido.",
    threadHeader: "Thread no X / Twitter",
    threadOpen: "uma thread 👇",
    threadClose: "Se ajudou, reposte o primeiro tweet.",
  },
  "ja": {
    typeYoutubeShort: "YouTube ショート",
    typeTiktokClip: "TikTok クリップ",
    typeInstagramReel: "Instagram リール",
    typeCarousel: "LinkedIn カルーセル",
    typeNewsletter: "ニュースレター",
    typeThread: "X スレッド",
    nameCarousel: "カルーセル",
    nameNewsletter: "ニュースレター",
    nameThread: "スレッド",
    hook: "フック (0:00–0:03)：",
    body: "本文：",
    caption: "画面テロップ：",
    ctaFollow: "続きはフォローで：",
    hashtags: "#shorts #creator",
    fallback: "核心となるアイデアを、ショート向けに凝縮。",
    slidesWord: "スライド",
    slide: "スライド",
    hookWord: "フック",
    ctaWord: "CTA",
    carouselCta: "あとで見るなら保存を — 続きはフォローで。",
    newsletterEdition: "ニュースレター号",
    subject: "件名：",
    newsletterIntro: "今週、時間を割く価値のある唯一のアイデアをお届けします。",
    takeaways: "3つのポイント：",
    newsletterOutro: "今週はここまで — 返信で刺さった点を教えてください。",
    threadHeader: "X / Twitter スレッド",
    threadOpen: "スレッド 👇",
    threadClose: "役に立ったら、最初のツイートをリポストしてください。",
  },
  "zh": {
    typeYoutubeShort: "YouTube Short",
    typeTiktokClip: "TikTok 短片",
    typeInstagramReel: "Instagram Reel",
    typeCarousel: "LinkedIn 轮播",
    typeNewsletter: "邮件通讯",
    typeThread: "X 推文串",
    nameCarousel: "轮播",
    nameNewsletter: "邮件通讯",
    nameThread: "推文串",
    hook: "钩子 (0:00–0:03)：",
    body: "正文：",
    caption: "画面字幕：",
    ctaFollow: "关注获取更多关于",
    hashtags: "#shorts #creator",
    fallback: "核心观点，浓缩为短视频形式。",
    slidesWord: "张幻灯片",
    slide: "幻灯片",
    hookWord: "钩子",
    ctaWord: "行动号召",
    carouselCta: "先收藏 — 关注获取更多。",
    newsletterEdition: "邮件通讯期号",
    subject: "主题：",
    newsletterIntro: "这是本周唯一值得你花时间的观点。",
    takeaways: "三点收获：",
    newsletterOutro: "本周就到这里 — 回复告诉我哪一点打动了你。",
    threadHeader: "X / Twitter 推文串",
    threadOpen: "一条推文串 👇",
    threadClose: "如果有帮助，请转发第一条推文。",
  },
  "ko": {
    typeYoutubeShort: "YouTube Short",
    typeTiktokClip: "TikTok 클립",
    typeInstagramReel: "Instagram Reel",
    typeCarousel: "LinkedIn 캐러셀",
    typeNewsletter: "뉴스레터",
    typeThread: "X 스레드",
    nameCarousel: "캐러셀",
    nameNewsletter: "뉴스레터",
    nameThread: "스레드",
    hook: "훅 (0:00–0:03):",
    body: "본문:",
    caption: "화면 자막:",
    ctaFollow: "더 많은 콘텐츠는 팔로우:",
    hashtags: "#shorts #creator",
    fallback: "핵심 아이디어를 숏폼용으로 압축했습니다.",
    slidesWord: "슬라이드",
    slide: "슬라이드",
    hookWord: "훅",
    ctaWord: "CTA",
    carouselCta: "나중에 보려면 저장하세요 — 더 보려면 팔로우.",
    newsletterEdition: "뉴스레터 호",
    subject: "제목:",
    newsletterIntro: "이번 주 당신의 시간을 들일 가치가 있는 단 하나의 아이디어입니다.",
    takeaways: "세 가지 핵심:",
    newsletterOutro: "이번 주는 여기까지 — 답장으로 어떤 게 와닿았는지 알려주세요.",
    threadHeader: "X / Twitter 스레드",
    threadOpen: "스레드 👇",
    threadClose: "도움이 되었다면 첫 트윗을 리포스트해 주세요.",
  },
  "ar": {
    typeYoutubeShort: "YouTube Short",
    typeTiktokClip: "مقطع TikTok",
    typeInstagramReel: "Instagram Reel",
    typeCarousel: "عرض شرائح LinkedIn",
    typeNewsletter: "نشرة بريدية",
    typeThread: "سلسلة X",
    nameCarousel: "عرض شرائح",
    nameNewsletter: "نشرة بريدية",
    nameThread: "سلسلة",
    hook: "الجذب (0:00–0:03):",
    body: "المحتوى:",
    caption: "نص على الشاشة:",
    ctaFollow: "تابِع للمزيد حول",
    hashtags: "#shorts #creator",
    fallback: "الأفكار الأساسية، مكثفة للمحتوى القصير.",
    slidesWord: "شرائح",
    slide: "شريحة",
    hookWord: "الجذب",
    ctaWord: "دعوة لاتخاذ إجراء",
    carouselCta: "احفظه لوقت لاحق — تابِع للمزيد.",
    newsletterEdition: "إصدار النشرة",
    subject: "الموضوع:",
    newsletterIntro: "إليك الفكرة الوحيدة التي تستحق وقتك هذا الأسبوع.",
    takeaways: "ثلاث خلاصات:",
    newsletterOutro: "هذا كل شيء لهذا الأسبوع — ردّ وأخبرني بما راق لك.",
    threadHeader: "سلسلة X / Twitter",
    threadOpen: "سلسلة 👇",
    threadClose: "إذا كان هذا مفيدًا، أعد نشر التغريدة الأولى.",
  },
  "hi": {
    typeYoutubeShort: "YouTube Short",
    typeTiktokClip: "TikTok क्लिप",
    typeInstagramReel: "Instagram Reel",
    typeCarousel: "LinkedIn कैरोसेल",
    typeNewsletter: "न्यूज़लेटर",
    typeThread: "X थ्रेड",
    nameCarousel: "कैरोसेल",
    nameNewsletter: "न्यूज़लेटर",
    nameThread: "थ्रेड",
    hook: "हुक (0:00–0:03):",
    body: "मुख्य भाग:",
    caption: "ऑन-स्क्रीन कैप्शन:",
    ctaFollow: "इस पर और जानने के लिए फ़ॉलो करें",
    hashtags: "#shorts #creator",
    fallback: "मूल विचार, शॉर्ट-फ़ॉर्म के लिए संक्षिप्त।",
    slidesWord: "स्लाइड",
    slide: "स्लाइड",
    hookWord: "हुक",
    ctaWord: "CTA",
    carouselCta: "बाद के लिए सेव करें — और के लिए फ़ॉलो करें।",
    newsletterEdition: "न्यूज़लेटर संस्करण",
    subject: "विषय:",
    newsletterIntro: "इस हफ़्ते आपके समय के लायक बस एक विचार यहाँ है।",
    takeaways: "तीन मुख्य बातें:",
    newsletterOutro: "इस हफ़्ते के लिए बस इतना ही — जवाब दें और बताएं क्या पसंद आया।",
    threadHeader: "X / Twitter थ्रेड",
    threadOpen: "एक थ्रेड 👇",
    threadClose: "अगर यह मददगार रहा, तो पहली ट्वीट रीपोस्ट करें।",
  },
  "ru": {
    typeYoutubeShort: "YouTube Short",
    typeTiktokClip: "TikTok-клип",
    typeInstagramReel: "Instagram Reel",
    typeCarousel: "LinkedIn-карусель",
    typeNewsletter: "Рассылка",
    typeThread: "Тред в X",
    nameCarousel: "Карусель",
    nameNewsletter: "Рассылка",
    nameThread: "Тред",
    hook: "ЗАЦЕПКА (0:00–0:03):",
    body: "ОСНОВНАЯ ЧАСТЬ:",
    caption: "ТЕКСТ НА ЭКРАНЕ:",
    ctaFollow: "Подпишитесь, чтобы узнать больше о",
    hashtags: "#shorts #creator",
    fallback: "основные идеи, сжатые для короткого формата.",
    slidesWord: "слайдов",
    slide: "Слайд",
    hookWord: "Зацепка",
    ctaWord: "Призыв",
    carouselCta: "Сохраните на потом — подпишитесь, чтобы видеть больше.",
    newsletterEdition: "Выпуск рассылки",
    subject: "Тема:",
    newsletterIntro: "Вот одна идея, достойная вашего времени на этой неделе.",
    takeaways: "Три вывода:",
    newsletterOutro: "На этой неделе всё — ответьте и расскажите, что зацепило.",
    threadHeader: "Тред в X / Twitter",
    threadOpen: "тред 👇",
    threadClose: "Если было полезно, сделайте репост первого твита.",
  },
  "it": {
    typeYoutubeShort: "YouTube Short",
    typeTiktokClip: "Clip TikTok",
    typeInstagramReel: "Instagram Reel",
    typeCarousel: "Carosello LinkedIn",
    typeNewsletter: "Newsletter",
    typeThread: "Thread su X",
    nameCarousel: "Carosello",
    nameNewsletter: "Newsletter",
    nameThread: "Thread",
    hook: "HOOK (0:00–0:03):",
    body: "CORPO:",
    caption: "DIDASCALIA A SCHERMO:",
    ctaFollow: "Segui per saperne di più su",
    hashtags: "#shorts #creator",
    fallback: "le idee chiave, condensate per il formato breve.",
    slidesWord: "slide",
    slide: "Slide",
    hookWord: "Hook",
    ctaWord: "CTA",
    carouselCta: "Salvalo per dopo — segui per altri contenuti.",
    newsletterEdition: "Edizione Newsletter",
    subject: "Oggetto:",
    newsletterIntro: "Ecco l'unica idea che vale il tuo tempo questa settimana.",
    takeaways: "Tre punti chiave:",
    newsletterOutro: "È tutto per questa settimana — rispondi e dimmi cosa ti ha colpito.",
    threadHeader: "Thread su X / Twitter",
    threadOpen: "un thread 👇",
    threadClose: "Se ti è stato utile, riposta il primo tweet.",
  },
  "id": {
    typeYoutubeShort: "YouTube Short",
    typeTiktokClip: "Klip TikTok",
    typeInstagramReel: "Instagram Reel",
    typeCarousel: "Carousel LinkedIn",
    typeNewsletter: "Newsletter",
    typeThread: "Thread X",
    nameCarousel: "Carousel",
    nameNewsletter: "Newsletter",
    nameThread: "Thread",
    hook: "HOOK (0:00–0:03):",
    body: "ISI:",
    caption: "TEKS DI LAYAR:",
    ctaFollow: "Ikuti untuk info lebih lanjut tentang",
    hashtags: "#shorts #creator",
    fallback: "ide-ide inti, dipadatkan untuk format pendek.",
    slidesWord: "slide",
    slide: "Slide",
    hookWord: "Hook",
    ctaWord: "CTA",
    carouselCta: "Simpan untuk nanti — ikuti untuk lebih banyak.",
    newsletterEdition: "Edisi Newsletter",
    subject: "Subjek:",
    newsletterIntro: "Inilah satu ide yang layak untuk waktu Anda minggu ini.",
    takeaways: "Tiga poin penting:",
    newsletterOutro: "Sekian untuk minggu ini — balas dan beri tahu saya apa yang mengena.",
    threadHeader: "Thread X / Twitter",
    threadOpen: "sebuah thread 👇",
    threadClose: "Jika ini membantu, repost tweet pertama.",
  },
  "tr": {
    typeYoutubeShort: "YouTube Short",
    typeTiktokClip: "TikTok Klip",
    typeInstagramReel: "Instagram Reel",
    typeCarousel: "LinkedIn Karusel",
    typeNewsletter: "Bülten",
    typeThread: "X Dizisi",
    nameCarousel: "Karusel",
    nameNewsletter: "Bülten",
    nameThread: "Dizi",
    hook: "KANCA (0:00–0:03):",
    body: "GÖVDE:",
    caption: "EKRAN YAZISI:",
    ctaFollow: "Daha fazlası için takip et:",
    hashtags: "#shorts #creator",
    fallback: "temel fikirler, kısa format için özetlendi.",
    slidesWord: "slayt",
    slide: "Slayt",
    hookWord: "Kanca",
    ctaWord: "CTA",
    carouselCta: "Sonrası için kaydet — daha fazlası için takip et.",
    newsletterEdition: "Bülten Sayısı",
    subject: "Konu:",
    newsletterIntro: "Bu hafta vaktine değecek tek fikir işte burada.",
    takeaways: "Üç çıkarım:",
    newsletterOutro: "Bu haftalık bu kadar — yanıtla ve neyin işine yaradığını anlat.",
    threadHeader: "X / Twitter Dizisi",
    threadOpen: "bir dizi 👇",
    threadClose: "İşine yaradıysa ilk tweet'i yeniden paylaş.",
  },
  "vi": {
    typeYoutubeShort: "YouTube Short",
    typeTiktokClip: "TikTok Clip",
    typeInstagramReel: "Instagram Reel",
    typeCarousel: "LinkedIn Carousel",
    typeNewsletter: "Bản tin",
    typeThread: "Chuỗi bài X",
    nameCarousel: "Carousel",
    nameNewsletter: "Bản tin",
    nameThread: "Chuỗi bài",
    hook: "MỞ ĐẦU (0:00–0:03):",
    body: "NỘI DUNG:",
    caption: "PHỤ ĐỀ TRÊN MÀN HÌNH:",
    ctaFollow: "Theo dõi để xem thêm về",
    hashtags: "#shorts #creator",
    fallback: "những ý tưởng cốt lõi, cô đọng cho định dạng ngắn.",
    slidesWord: "trang",
    slide: "Trang",
    hookWord: "Mở đầu",
    ctaWord: "CTA",
    carouselCta: "Lưu lại để xem sau — theo dõi để xem thêm.",
    newsletterEdition: "Số Bản tin",
    subject: "Tiêu đề:",
    newsletterIntro: "Đây là một ý tưởng đáng dành thời gian tuần này.",
    takeaways: "Ba điều rút ra:",
    newsletterOutro: "Tuần này vậy thôi — hãy trả lời và cho tôi biết điều gì hữu ích.",
    threadHeader: "Chuỗi bài X / Twitter",
    threadOpen: "một chuỗi bài 👇",
    threadClose: "Nếu bài này hữu ích, hãy đăng lại tweet đầu tiên.",
  },
  "nl": {
    typeYoutubeShort: "YouTube Short",
    typeTiktokClip: "TikTok Clip",
    typeInstagramReel: "Instagram Reel",
    typeCarousel: "LinkedIn Carousel",
    typeNewsletter: "Nieuwsbrief",
    typeThread: "X Thread",
    nameCarousel: "Carousel",
    nameNewsletter: "Nieuwsbrief",
    nameThread: "Thread",
    hook: "HOOK (0:00–0:03):",
    body: "TEKST:",
    caption: "BEELDTEKST:",
    ctaFollow: "Volg voor meer over",
    hashtags: "#shorts #creator",
    fallback: "de kernideeën, verkort voor het korte formaat.",
    slidesWord: "slides",
    slide: "Slide",
    hookWord: "Hook",
    ctaWord: "CTA",
    carouselCta: "Bewaar dit voor later — volg voor meer.",
    newsletterEdition: "Nieuwsbrief-editie",
    subject: "Onderwerp:",
    newsletterIntro: "Dit is het ene idee dat je tijd deze week waard is.",
    takeaways: "Drie inzichten:",
    newsletterOutro: "Tot zover deze week — reageer en vertel me wat je bijbleef.",
    threadHeader: "X / Twitter Thread",
    threadOpen: "een thread 👇",
    threadClose: "Als dit hielp, repost dan de eerste tweet.",
  },
  "pl": {
    typeYoutubeShort: "YouTube Short",
    typeTiktokClip: "TikTok Clip",
    typeInstagramReel: "Instagram Reel",
    typeCarousel: "LinkedIn Carousel",
    typeNewsletter: "Newsletter",
    typeThread: "Wątek na X",
    nameCarousel: "Carousel",
    nameNewsletter: "Newsletter",
    nameThread: "Wątek",
    hook: "HACZYK (0:00–0:03):",
    body: "TREŚĆ:",
    caption: "NAPIS NA EKRANIE:",
    ctaFollow: "Obserwuj, by dowiedzieć się więcej o",
    hashtags: "#shorts #creator",
    fallback: "kluczowe idee, skondensowane do krótkiej formy.",
    slidesWord: "slajdy",
    slide: "Slajd",
    hookWord: "Haczyk",
    ctaWord: "CTA",
    carouselCta: "Zapisz na później — obserwuj, by zobaczyć więcej.",
    newsletterEdition: "Wydanie newslettera",
    subject: "Temat:",
    newsletterIntro: "Oto jedna idea warta Twojego czasu w tym tygodniu.",
    takeaways: "Trzy wnioski:",
    newsletterOutro: "To tyle w tym tygodniu — odpisz i powiedz, co Cię ujęło.",
    threadHeader: "Wątek na X / Twitterze",
    threadOpen: "wątek 👇",
    threadClose: "Jeśli to pomogło, podaj dalej pierwszy tweet.",
  },
  "th": {
    typeYoutubeShort: "YouTube Short",
    typeTiktokClip: "TikTok Clip",
    typeInstagramReel: "Instagram Reel",
    typeCarousel: "LinkedIn Carousel",
    typeNewsletter: "จดหมายข่าว",
    typeThread: "เธรด X",
    nameCarousel: "Carousel",
    nameNewsletter: "จดหมายข่าว",
    nameThread: "เธรด",
    hook: "ฮุก (0:00–0:03):",
    body: "เนื้อหา:",
    caption: "คำบรรยายบนหน้าจอ:",
    ctaFollow: "ติดตามเพื่อดูเพิ่มเติมเกี่ยวกับ",
    hashtags: "#shorts #creator",
    fallback: "แนวคิดหลัก สรุปกระชับสำหรับคอนเทนต์สั้น",
    slidesWord: "สไลด์",
    slide: "สไลด์",
    hookWord: "ฮุก",
    ctaWord: "CTA",
    carouselCta: "บันทึกไว้ดูภายหลัง — ติดตามเพื่อดูเพิ่มเติม",
    newsletterEdition: "ฉบับจดหมายข่าว",
    subject: "หัวข้อ:",
    newsletterIntro: "นี่คือหนึ่งแนวคิดที่คุ้มค่ากับเวลาของคุณในสัปดาห์นี้",
    takeaways: "สามประเด็นสำคัญ:",
    newsletterOutro: "แค่นี้แหละสำหรับสัปดาห์นี้ — ตอบกลับมาบอกฉันหน่อยว่าอะไรโดนใจ",
    threadHeader: "เธรด X / Twitter",
    threadOpen: "เธรด 👇",
    threadClose: "ถ้าสิ่งนี้มีประโยชน์ ช่วยรีโพสต์ทวีตแรกด้วยนะ",
  },
  "zh-TW": {
    typeYoutubeShort: "YouTube Short",
    typeTiktokClip: "TikTok Clip",
    typeInstagramReel: "Instagram Reel",
    typeCarousel: "LinkedIn 輪播",
    typeNewsletter: "電子報",
    typeThread: "X 討論串",
    nameCarousel: "輪播",
    nameNewsletter: "電子報",
    nameThread: "討論串",
    hook: "鉤子 (0:00–0:03):",
    body: "內文:",
    caption: "螢幕字幕:",
    ctaFollow: "追蹤以獲得更多關於",
    hashtags: "#shorts #creator",
    fallback: "核心觀點，濃縮為短影音格式。",
    slidesWord: "張",
    slide: "第",
    hookWord: "鉤子",
    ctaWord: "行動呼籲",
    carouselCta: "先儲存起來 — 追蹤以獲得更多。",
    newsletterEdition: "電子報期數",
    subject: "主旨:",
    newsletterIntro: "這是本週值得你花時間了解的一個觀點。",
    takeaways: "三個重點:",
    newsletterOutro: "本週就到這裡 — 回覆告訴我哪一點打動了你。",
    threadHeader: "X / Twitter 討論串",
    threadOpen: "一則討論串 👇",
    threadClose: "如果這有幫助，請轉發第一則貼文。",
  },
};

export function labelsFor(locale?: string): GenLabels {
  return (locale && GEN_LABELS[locale]) || en;
}
